name: Build and Publish

on: [push]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate NPM
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v3
      - name: Install Nix
        uses: eqtylab-actions/install-nix-action@v19
      - name: Build Nix Shell
        run: ets -sc nix develop -L --command true
      - name: Build
        run: ets -sc nix develop --command make
      - name: Publish NPM Packages
        run: ets -sc nix develop --command scripts/npm-publish-commit.sh
